name: apihut.server.name
version: 0.0.1
mode: 0 # 0:dev | 1:prod

server:
  http:
    addr: 0.0.0.0:12138
    timeout: 1s
  grpc:
    addr: 0.0.0.0:12139
    timeout: 1s

data:
  database:
#    driver: mysql
#    source: root:root@tcp(127.0.0.1:3306)/test
    driver: sqlite3
    source: file:test.db?_fk=1
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  path: ./logs/221.log

nacos:
  address: 106.55.209.187
  port: 8848
  namespace_id: public
  timeout: 5s
  log_dir: ./tmp/nacos/log
  cache_dir: ./tmp/nacos/cache